services:
  nginx:
    image: tiangolo/nginx-rtmp
    ports:
      - "80:80"
      - "1935:1935"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/hls:/tmp/hls
    depends_on:
      - stream-api
    networks:
      - stream-net

  stream-api:
    build: ./stream-api
    environment:
      - PORT=3000
      - TRANSCODER_SERVICE_ADDRESS=http://transcoder:3000
      - MONGO_HOST=mongo
    depends_on:
      - transcoder
    networks:
      - stream-net

  transcoder:
    build: ./transcoder
    environment:
      - PORT=3000
      - STREAM_API_HOST=stream-api:3000
      - RTMP_SERVER=nginx:1935
    networks:
      - stream-net
  viewer-api:
    build: ./viewer-api
    environment:
      - PORT=3000
      - STREAM_API_HOST=stream-api:3000
    networks:
      - stream-net
  mongo:
    image: 'mongo:latest'
    ports:
      - '27010:27017'
    volumes:
      - ./data:/data/db
    networks:
      - stream-net
networks:
  stream-net:
    driver: bridge
